{{- if .Values.customConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fluentd.fullname" . }}-custom-config
  labels:
    {{- include "fluentd.labels" . | nindent 4 }}
data:
  fluent.conf: |
    @include config.d/*.conf

    # Receive events from 24224/tcp
    # This is used by log forwarding and the fluent-cat command
    <source>
      @type forward
      port {{ .Values.service.port }}
      bind 0.0.0.0
    </source>
{{- end }}
---
{{- if and (.Values.customConfig) (.Values.extraConfig) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fluentd.fullname" . }}-extra-config
  labels:
    {{- include "fluentd.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.extraConfigData }}
  {{ $key }}: |-
{{ $value | indent 4 }}
{{- end }}
{{- end }}